--- # App

# Setup shared files and folders

- name: make dirs
  file:
    path={{ item }}
    state=directory
    owner={{ unicorn_user }}
  with_items:
    - "{{ app_path }}"
    - "{{ shared_path }}"
    - "{{ backup_path }}"
    - "{{ releases_path }}"
    - "{{ system_path }}"
    - "{{ images_path }}"
    - "{{ files_path }}"
    - "{{ spree_path }}"
    - "{{ log_path }}"
    - "{{ pid_path }}"
    - "{{ sock_path }}"
    - "{{ config_path }}"
  tags: dirs

# The .pgpass file enables us to access the database with psql or
# pgdump without entering a password. It is not required but makes
# sysadmin and dev tasks more convenient.
- name: add .pgpass file for {{ unicorn_user }}
  template:
    src: pgpass.j2
    dest: "{{ unicorn_home_path }}/.pgpass"
    owner: "{{ unicorn_user }}"
    mode: 0600
  become: yes
  become_user: "{{ unicorn_user }}"

- name: template files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ unicorn_user }}
    mode=0775
  with_items:
    - { src: "application.yml.j2", dest: "{{ config_path }}/application.yml" }
    - { src: "postgresql.yml.j2", dest: "{{ config_path }}/database.yml" }
  tags: app_templates

- name: get l10n repo
  git:
    repo={{ l10n_repo }}
    dest={{ l10n_path }}
    version={{ l10n_git_version }}
    force=yes
  tags: l10n


